- type: job
  id: JediNT
  name: job-name-jedi-nt
  description: job-description-jedi-nt
  playTimeTracker: JobJediNT
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 18000 # 5 hours
  startingGear: JediNTGear
  icon: "JobIconJediNT"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: JediNTGear
  equipment:
    shoes: ClothingShoesBootsSpetsnazFilled
    ears: ClothingHeadsetAltSecurity
    gloves: ClothingHandsGlovesCombat
    id: JediNTPDA
    eyes: ClothingEyesGlassesSunglassesModified

- type: chameleonOutfit
  id: JediNTChameleonOutfit
  job: JediNT
  hasMindShield: true
  equipment:
    head: ClothingHeadHatJediNTBeret
    mask: ClothingMaskGasJediNT
    neck: ClothingNeckMantleJediNT
    belt: ClothingBeltJediNTBelt
