- type: job
  id: RoboticistGenesis
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticistGenesis
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 14400 # 4 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400 # 4 hrs
  startingGear: RoboticistGenesisGear
  icon: JobIconRoboticist
  supervisors: job-supervisors-rd
  access:
    - Research
    - Maintenance
    - Engineering

- type: startingGear
  id: RoboticistGenesisGear
  equipment:
    id: RoboticistPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetRobotics

- type: chameleonOutfit
  id: RoboticistGenesisChameleonOutfit
  job: Roboticist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
