- type: job
  id: CentralCommandAssistant
  name: job-name-centcom-assistant
  description: job-description-centcom-assistant
  playTimeTracker: JobCentralCommandAssistant
  startingGear: CentComAssistantGear
  icon: "JobIconCentComService"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  - CentralCommand
  - Hydroponics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CentComAssistantGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CentComAssistantPDA
    ears: ClothingHeadsetCentCom
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: CentComAssistantChameleonOutfit
  job: CentralCommandAssistant
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckMantle
