- type: job
  id: CentComConsultant
  name: job-name-consultant
  description: job-description-consultant
  playTimeTracker: JobCentComConsultant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 468000  # 130 hours
  startingGear: ConsultantGear
  icon: "JobIconNanotrasen"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Command
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - CentralCommand
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ConsultantGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglassesModified
    gloves: ClothingHandsGlovesLatex
    id: CentcomConsultantPDA
    ears: ClothingHeadsetCentCom
    belt: BoxFolderClipboard
    pocket1: WeaponDisabler
  storage:
    back:
    - BoxSurvival
    - Flash
    - TelescopicBaton

- type: chameleonOutfit
  id: ConsultantChameleonOutfit
  job: CentComConsultant
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCentcomConsultantCap
    eyes: ClothingEyesGlassesSunglassesModified
    gloves: ClothingHandsGlovesLatex
    outerClothing: ClothingOuterCoatCentcomConsultant
