- type: job
  id: CentralCommandEngineer
  name: job-name-centcom-engineering
  description: job-description-engineer
  playTimeTracker: JobCentralCommandEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400 #4 hrs
    - !type:DepartmentTimeRequirement
      department: CentralCommand
      time: 14400 #4 hrs
  startingGear: CentComEngineerGear
  icon: "JobIconCentComEngineering"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CentComEngineerGear
  equipment:
    id: CentComEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetCentCom
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: CentComEngineerChameleonOutfit
  job: CentralCommandEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
